// <auto-generated />
using System;
using Clinic_Veterinaty_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clinic_Veterinaty_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220726161446_DataOfTables")]
    partial class DataOfTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Clinic_Veterinaty_API.Models.Client", b =>
                {
                    b.Property<ulong>("CPF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CPF");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Clinic_Veterinaty_API.Models.Dog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("ClientsCPF")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("DogBreed")
                        .HasColumnType("longtext");

                    b.Property<double>("DogHeight")
                        .HasColumnType("double");

                    b.Property<double>("DogWeight")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClientsCPF");

                    b.ToTable("Dogs");
                });

            modelBuilder.Entity("Clinic_Veterinaty_API.Models.User", b =>
                {
                    b.Property<ulong>("Identification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("JobRole")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Identification");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Clinic_Veterinaty_API.Models.Vet", b =>
                {
                    b.Property<int>("CRMV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("CRMV");

                    b.ToTable("Vets");
                });

            modelBuilder.Entity("Clinic_Veterinaty_API.Models.VetCare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Age")
                        .HasColumnType("double");

                    b.Property<ulong?>("ClientsCPF")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Coments")
                        .HasColumnType("longtext");

                    b.Property<int?>("DogsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastDiagnosis")
                        .HasColumnType("longtext");

                    b.Property<int?>("VetsCRMV")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ClientsCPF");

                    b.HasIndex("DogsId");

                    b.HasIndex("VetsCRMV");

                    b.ToTable("VetCare");
                });

            modelBuilder.Entity("Clinic_Veterinaty_API.Models.Dog", b =>
                {
                    b.HasOne("Clinic_Veterinaty_API.Models.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientsCPF");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("Clinic_Veterinaty_API.Models.VetCare", b =>
                {
                    b.HasOne("Clinic_Veterinaty_API.Models.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientsCPF");

                    b.HasOne("Clinic_Veterinaty_API.Models.Dog", "Dogs")
                        .WithMany()
                        .HasForeignKey("DogsId");

                    b.HasOne("Clinic_Veterinaty_API.Models.Vet", "Vets")
                        .WithMany()
                        .HasForeignKey("VetsCRMV");

                    b.Navigation("Clients");

                    b.Navigation("Dogs");

                    b.Navigation("Vets");
                });
#pragma warning restore 612, 618
        }
    }
}
